name:                monadic-llparser
version:             0.1.0.0
github:              "githubuser/monadic-llparser"
license:             BSD3
author:              "Michael Pettenato"
maintainer:          "mp34@illinois.edy"
copyright:           "2022 Michael Pettenato"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/monadic-llparser#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers >= 0.2
- mtl

library:
  source-dirs: src
  exposed-modules:
    - Parser


executables:
  monadic-llparser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadic-llparser

tests:
  monadic-llparser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadic-llparser
    - QuickCheck >= 2.9.0
    - HUnit >= 1.5
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-io
